### ISSUE TITLE
How to use Alpaca Websocket

### ISSUE THREAD

**Issue by geofffoster** [mdkrieg/node-red-contrib-alpaca#2]
Hi, nice bit of work. I've been trying to figure out how to use the Alpaca Websocket, do you have a simple example? I can connect a debug node and see it is connecting/disconnecting fine.

**Comment by mdkrieg** [comment]
Hi, glad you like the package. The Websocket node may not be actually
finished, I'm a little fuzzy myself on what the function from the SDK does.

updates_client.onConnect(function () {
>     console.log("Alpaca Event Listener Connected");
>     const trade_keys = ['trade_updates', 'account_updates'];
>     updates_client.subscribe(trade_keys);
> });
>

So the current node just listens for "trade_update" and "account updates",
I'd assume that this gives you an update any time a trade is filled or your
account status changes (added funds, day trade status, stuff like that
maybe?).

I need to figure out what else this Websocket is capable of and how a user
would want to configure it. Let me know if you already have some idea of
what you want to use the websocket for so I can make sure to accommodate.

Also, check out the official alpaca node sdk:
https://github.com/alpacahq/alpaca-trade-api-js  There's an example there
that is more or less what I used as the template.

Regards,
-Matt

**Comment by geofffoster** [comment]
Hi Matt,
Alpaca has its on datasource, and if you have a live account you get access to polygon.io's feed. This higher quality data, including tick data (well this i my use case).
You can subscirbe to live data feed - say AAPL and get real time prices streamed.
Unfortunately I'm a python guy - but I'm having a read through the javascript code

regards
Geoff

**Comment by mdkrieg** [comment]
I did some work on an update today. Created the Alpaca-Datasocket node

Currently only accepts a single subscription key (such as T.FB or Q.AAPL)

`npm install https://github.com/mdkrieg/node-red-contrib-alpaca#ws-patch-1`

Full disclosure, haven't tested this on a live market yet, I'm kindof assuming that's why it doesn't connect atm

**Comment by geofffoster** [comment]
A quick test and its returning daily OHLCV - I'll see if I can get tick on the weekend. Good work btw

**Comment by mdkrieg** [comment]
Hello,

If you're still interested, I've recently done quite a bit of work on the project and I've got a websocket node that uses the data v2 api and it seems to work quite well in my testing.

I've abandoned the previous socket nodes I made as I was never able to get it to work.

Best regards!
-Matt

**Comment by geofffoster** [comment]
Hi,
  
I'll have a look this weekend
  
Regards
  
Geoff
  

  

  

  
  
  
  
>
